export {
  buildLanguageInstruction,
  detectLanguage,
  detectLanguageFromAudioMeta,
  getLanguageLabel,
  isConfidentLanguageSwitch,
  LANGUAGE_LABELS,
  LANGUAGE_MODE_OPTIONS,
  normalizeLanguageCode,
  resolveSttLocale,
  toScribeLanguageCode,
  type LanguageCode,
  type LanguageMode,
  type SupportedLanguage,
} from '@voiceify/shared';
