import type { VoiceAgentRecord } from './voice-agent-runtime';

/** Default workspace agents — demo, sandbox, and dashboard all read from this list. */
export const DEFAULT_VOICE_AGENTS: VoiceAgentRecord[] = [
  {
    id: 1,
    name: 'Nova',
    type: 'Restaurant',
    personaId: 'restaurant',
    isDemoDefault: true,
    language: 'English/Urdu',
    status: 'Active',
    capabilities: ['Reservations', 'Menu Info', 'Multilingual'],
    triggers: ['book a table', 'menu', 'reservation'],
    voice: 'Puck',
  },
  {
    id: 2,
    name: 'Dr. Sarah',
    type: 'Healthcare',
    personaId: 'healthcare',
    isDemoDefault: true,
    language: 'English/Urdu',
    status: 'Active',
    capabilities: ['Appointment Booking', 'Symptom Check', 'Patient History'],
    triggers: ['pain', 'appointment'],
    voice: 'Kore',
  },
  {
    id: 3,
    name: 'Alex',
    type: 'Customer Service',
    personaId: 'support',
    isDemoDefault: true,
    language: 'English/Urdu',
    status: 'Active',
    capabilities: ['Order Tracking', 'Refund Processing', 'FAQ'],
    triggers: ['refund', 'where is my order'],
    voice: 'Puck',
  },
  {
    id: 4,
    name: 'Real Estate Pro',
    type: 'Real Estate',
    personaId: 'restaurant',
    isDemoDefault: false,
    language: 'English',
    status: 'Inactive',
    capabilities: ['Property Listing', 'Virtual Tour', 'Price Negotiation'],
    triggers: ['price', 'location'],
    voice: 'Fenrir',
  },
];
